= differential-drive

This is a slightly modified version of the `differential_drive`
ROS package written by Jon Stephan, and modified by Mark Rose.

ROS package page::
http://wiki.ros.org/differential_drive

Jon Stephan&rsquo;s repository location::
https://github.com/jfstepha/differential-drive

diff_tf and pid_velocity have both been modified to
read a custom message with the following definition:
```python
int32 leftTicks
int32 rightTicks
```
They read these messages from the "/odom/encTicks" topic,
but that can easily be remapped in your launch file. diff_tf
also no longer publishes an odom -> base_link transform
to tf, since it is meant to be used as input to the
robot_localization package, which will publish its own
transform after fusing that dead reckoning estimate with
other sensors. A 'which_wheel' param was added to
pid_velocity, to tell the code which field of my custom
message to read.

== License

The code is licensed under the terms of the Gnu General Public
License, Version 3. See the file `LICENSE` for details.
